export default {
  "name": "Arn Hachem",
  "type": ["human", "sanctified", "deathless", "spellstitched", "archlich"],
  "hitPoints": {
    "dieSize": 12,
    "total": 255,
    "damage": 0,
    "temporaryHitPoints": 0,
  },
  "armorClass": {
    "ac": {
      "total": 37,
      "armor": 6,
      "shield": 0,
      "dexterity": 12,
      "size": 0,
      "naturalArmor": 5,
      "deflection": 4,
      "misc": 0
    },
    "touch": 22,
    "flatFooted": 23
  },
  "size": "Medium",
  "alignment": "Lawful-Good",
  "abilities": {
    "score": {
      "strength": 18,
      "dexterity": 24,
      "constitution": "--",
      "intelligence": 22,
      "wisdom": 17,
      "charisma": 35
    },
  },
  "speed": 30,
  "level": "20",
  "class": ["Sorcerer(1)", "Mindtender(2)", "Fleshwarper(2)", "Malconvoker(7)", "Binder(1)", "Bard(1)", "Master of Masks(5)"],
  "skills": {
    "appraise": 10,
    "balance": 12,
    "bluff": 41,
    "climb": 4,
    "concentration": 27,
    "craft": 13,
    "diplomacy": 18,
    "diguise": 39,
    "escapeArtist": 12,
    "forgery": 6,
    "gatherInformation": 9,
    "heal": 16,
    "hide": 25,
    "intimidate": 19,
    "jump": 4,
    "listen": 4,
    "moveSilently": 12,
    "ride": 12,
    "search": 6,
    "senseMotive": 21,
    "spot": 4,
    "survival": 4,
    "swim": 12,
    "useRope": 12,
    "stealth": 28,
    "perception": 19
  },
  "classSkills": {
    "knowledgeArcana": 26,
    "knowledgeDungeoneering": 14,
    "knowledgeReligion": 16,
    "knowledgePlanes": 8,
  },
  "characterAbilities": [
    "Light_Ray", "Paralyzing_Touch", "Positive_Energy_Touch", "Turn_Undead"
  ],
  "magic": {
    "slas": {
      "zero": "",
      "one": ["Chill_Touch", "Floating_Disk"],
      "two": ["Command_Undead", "Acid_Arrow"],
      "three": ["Vampiric_Touch", "Phantom_Steed"],
      "four": ["Affliction", "Enervation"],
      "five": ["Mage\'s_Faithful_Hound", "Wall_of_Force"],
      "six": ["Contingency"],
      "seven": "",
      "eight": "",
      "nine": "",
    },
    "spellcaster": true,
    "type": {
      "arcane": true,
      "divine": false,
    },
    "spells": {
      "zero": ["Mending", "Arcane_Mark", "Ghost_Sound", "Detect_Magic", "Mage_Hand", "Message", "Light", "Read Magic", "Acid_Splash", "Lullaby", "Know_Direction", "Open/Close", "Prestidigitation"],
      "one": ["Silent_Image", "Disguise_Self", "Magic_Missile", "Mage_Armor", "Charm_Person"],
      "two": ["Ghoul_Touch", "Arcane_Lock", "Knock", "Alter_Fortune", "Scorching_Ray"],
      "three": ["Shrink_Item", "Tiny_Hut", "Ray_of_Exhaustion", "Explosive_Runes"],
      "four": ["Resilient_Sphere", "Create_Fetch", "Dimension_Door", "Polymorph"],
      "five": ["Telekinesis", "Sending", "Passwall", "Planar_Binding,_Lesser", "Feeblemind"],
      "six": ["Disintigrate", "Freezing_Sphere", "Planar_Binding", "Permanent_Image"],
      "seven": ["Teleport_Object", "Stun_Ray", "Waves_of_Exhaustion"],
      "eight": ["Polymorph_any_Object", "Horrid_Wilting", "Planar_Binding,_Greater", "Last_Judgment"],
      "nine": ["Replicate_Casting", "Sphere_of_Ultimate_Destruction", "Crushing_Hand"]
    },
    "spellbook": {
      "zero": ["Arcane_Mark", "Prestidigitation", "Mage_Hand", "Resistance", "Disrupt Undead", "Touch_of_Fatigue", "Mending", "Message", "Open/Close", "Preserve_Organ", "No-Light", "Slash_Tongue", "Silent_Portal"],
      "one": ["a"],
      "two": ["a"],
      "three": ["a"],
      "four": ["a"],
      "five": ["a"],
      "six": ["a"],
      "seven": ["a"],
      "eight": ["a"],
      "nine": ["a"],
    },
    "spellsPerDay": {
      "zero": 8,
      "one": 6,
      "two": 6,
      "three": 6,
      "four": 6,
      "five": 6,
      "six": 6,
      "seven": 6,
      "eight": 6,
      "nine": 6,
    },
  },
  "items": [
    "Mesmerist\'s Gloves", "Nolzure\'s Orb", "Vanisher Cloak", "GateBreaker Ballista Bolt"
  ],
}
