export const skills: CompendiumSkill[] = [
  {
    id: "0",
    name: "Appraise",
    ability: "intelligence",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "1",
    name: "Balance",
    ability: "dexterity",
    armorCheck: true,
    isDefault: true,
  },
  {
    id: "2",
    name: "Bluff",
    ability: "charisma",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "3",
    name: "Climb",
    ability: "strength",
    armorCheck: true,
    isDefault: true,
  },
  {
    id: "4",
    name: "Concentration",
    ability: "charisma",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "5",
    name: "Decipher Script",
    ability: "intelligence",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "6",
    name: "Diplomacy",
    ability: "charisma",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "7",
    name: "Disable Device",
    ability: "intelligence",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "8",
    name: "Disguise",
    ability: "charisma",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "9",
    name: "Escape Artist",
    ability: "dexterity",
    armorCheck: true,
    isDefault: true,
  },
  {
    id: "10",
    name: "Forgery",
    ability: "intelligence",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "11",
    name: "Gather Information",
    ability: "charisma",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "12",
    name: "Handle Animal",
    ability: "charisma",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "13",
    name: "Heal",
    ability: "wisdom",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "14",
    name: "Hide",
    ability: "dexterity",
    armorCheck: true,
    isDefault: false,
  },
  {
    id: "15",
    name: "Intimidate",
    ability: "charisma",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "16",
    name: "Jump",
    ability: "strength",
    armorCheck: true,
    isDefault: true,
  },
  {
    id: "17",
    name: "Listen",
    ability: "wisdom",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "18",
    name: "Move Silently",
    ability: "dexterity",
    armorCheck: true,
    isDefault: false,
  },
  {
    id: "19",
    name: "Open Lock",
    ability: "dexterity",
    armorCheck: true,
    isDefault: false,
  },
  {
    id: "20",
    name: "Ride",
    ability: "dexterity",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "21",
    name: "Search",
    ability: "intelligence",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "22",
    name: "Sense Motive",
    ability: "wisdom",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "23",
    name: "Sleight of Hand",
    ability: "dexterity",
    armorCheck: true,
    isDefault: false,
  },
  {
    id: "24",
    name: "Spellcraft",
    ability: "intelligence",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "25",
    name: "Spot",
    ability: "wisdom",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "26",
    name: "Survival",
    ability: "wisdom",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "27",
    name: "Swim",
    ability: "strength",
    armorCheck: true,
    isDefault: true,
  },
  {
    id: "28",
    name: "Tumble",
    ability: "dexterity",
    armorCheck: true,
    isDefault: true,
  },
  {
    id: "29",
    name: "Use Magic Device",
    ability: "charisma",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "30",
    name: "Use Rope",
    ability: "dexterity",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "31",
    name: "Knowledge Arcana",
    ability: "intelligence",
    armorCheck: false,
    isDefault: true,
  },
  {
    id: "32",
    name: "Knowledge Architecture and Engineering",
    ability: "intelligence",
    armorCheck: false,
    isDefault: false,
  },
  {
    id: "33",
    name: "Knowledge Dungeoneering",
    ability: "intelligence",
    armorCheck: false,
    isDefault: false,
  },
  {
    id: "34",
    name: "Knowledge Geography",
    ability: "intelligence",
    armorCheck: false,
    isDefault: false,
  },
  {
    id: "35",
    name: "Knowledge History",
    ability: "intelligence",
    armorCheck: false,
    isDefault: false,
  },
  {
    id: "36",
    name: "Knowledge Local",
    ability: "intelligence",
    armorCheck: false,
    isDefault: false,
  },
  {
    id: "37",
    name: "Knowledge Nature",
    ability: "intelligence",
    armorCheck: false,
    isDefault: false,
  },
  {
    id: "38",
    name: "Knowledge Nobility and Royalty",
    ability: "intelligence",
    armorCheck: false,
    isDefault: false,
  },
  {
    id: "39",
    name: "Knowledge the Planes",
    ability: "intelligence",
    armorCheck: false,
    isDefault: false,
  },
  {
    id: "40",
    name: "Perform Acting",
    ability: "charisma",
    armorCheck: false,
    isDefault: false,
  },
  {
    id: "41",
    name: "Perform Dancing",
    ability: "charisma",
    armorCheck: true,
    isDefault: false,
  },
  {
    id: "42",
    name: "Stealth",
    ability: "dexterity",
    armorCheck: true,
    isDefault: false,
  },
  {
    id: "43",
    name: "Craft Tailor",
    ability: "intelligence",
    armorCheck: false,
    isDefault: false,
  },
  {
    id: "44",
    name: "Knowledge Religion",
    ability: "intelligence",
    armorCheck: false,
    isDefault: false,
  },
  {
    id: "45",
    name: "Perception",
    ability: "wisdom",
    armorCheck: false,
    isDefault: false,
  },
];
