export default {
  name: "Arn Hachem",
  type: ["Human", "Sanctified", "Deathless", "Spellstitched", "Archlich"],
  hitPoints: {
    dieSize: 12,
    total: 255,
    damage: 0,
    temporaryHitPoints: 0,
  },
  armorClass: {
    ac: {
      total: 37,
      armor: 6,
      shield: 0,
      dexterity: 12,
      size: 0,
      naturalArmor: 5,
      deflection: 4,
      misc: 0,
    },
    touch: 22,
    flatFooted: 23,
  },
  size: "Medium",
  alignment: "Lawful-Good",
  abilities: {
    score: {
      strength: 18,
      dexterity: 24,
      constitution: null,
      intelligence: 22,
      wisdom: 17,
      charisma: 35,
    },
  },
  speed: 30,
  level: "20",
  class: [
    "Sorcerer(1)",
    "Mindtender(2)",
    "Fleshwarper(2)",
    "Malconvoker(7)",
    "Binder(1)",
    "Bard(1)",
    "Master Of Masks(5)",
  ],
  skills: {
    Balance: 12,
    Climb: 4,
    Concentration: 27,
    Escape_Artist: 12,
    Hide: 25,
    Jump: 4,
    Listen: 4,
    Move_Silently: 12,
    Ride: 12,
    Search: 6,
    Spot: 4,
    Survival: 4,
    Swim: 12,
    Use_Rope: 12,
  },
  classSkills: {
    Appraise: 10,
    Bluff: 41,
    Craft_Tailor: 13,
    Decipher_Script: 23,
    Diplomacy: 18,
    Diguise: 39,
    Forgery: 6,
    Gather_Information: 9,
    Heal: 16,
    Intimidate: 19,
    Knowledge_Arcana: 26,
    Knowledge_Dungeoneering: 14,
    Knowledge_Religion: 16,
    Knowledge_Planes: 8,
    Perception: 19,
    Perform_Acting: 36,
    Perform_Dancing: 13,
    SenseMotive: 21,
    Spellcraft: 28,
    Stealth: 28,
    Use_Magic_Device: 12,
  },
  characterAbilities: {
    active: [
      "Light_Ray",
      "Paralyzing_Touch",
      "Positive_Energy_Touch",
      "Turn_Undead",
    ],
    passive: ["Aura_Of_Menace"],
  },
  magic: {
    slas: {
      zero: "",
      one: ["Chill Touch", "Floating Disk"],
      two: ["Command Undead", "Acid Arrow"],
      three: ["Vampiric Touch", "Phantom Steed"],
      four: ["Affliction", "Enervation"],
      five: ["Mage's Faithful Hound", "Wall Of Force"],
      six: ["Contingency"],
      seven: "",
      eight: "",
      nine: "",
    },
    spellcaster: true,
    type: {
      arcane: true,
      divine: false,
    },
    spells: {
      zero: [
        "Mending",
        "Arcane Mark",
        "Ghost Sound",
        "Detect Magic",
        "Mage Hand",
        "Message",
        "Light",
        "Read Magic",
        "Acid Splash",
        "Lullaby",
        "Know Direction",
        "Open/Close",
        "Prestidigitation",
      ],
      one: [
        "Silent Image",
        "Disguise Self",
        "Magic Missile",
        "Mage Armor",
        "Charm Person",
      ],
      two: [
        "Ghoul Touch",
        "Arcane Lock",
        "Knock",
        "Alter Fortune",
        "Scorching Ray",
      ],
      three: [
        "Shrink Item",
        "Tiny Hut",
        "Ray Of Exhaustion",
        "Explosive Runes",
      ],
      four: ["Resilient Sphere", "Create Fetch", "Dimension Door", "Polymorph"],
      five: [
        "Telekinesis",
        "Sending",
        "Passwall",
        "Planar Binding, Lesser",
        "Feeblemind",
      ],
      six: [
        "Disintigrate",
        "Freezing Sphere",
        "Planar Binding",
        "Permanent Image",
      ],
      seven: ["Teleport Object", "Stun Ray", "Waves Of Exhaustion"],
      eight: [
        "Polymorph Any Object",
        "Horrid Wilting",
        "Planar Binding, Greater",
        "Last Judgment",
      ],
      nine: [
        "Replicate Casting",
        "Sphere Of Ultimate Destruction",
        "Crushing Hand",
      ],
    },
    spellbook: {
      zero: [
        "Arcane Mark",
        "Prestidigitation",
        "Mage Hand",
        "Resistance",
        "Disrupt Undead",
        "Touch Of Fatigue",
        "Mending",
        "Message",
        "Open/Close",
        "Preserve Organ",
        "No-Light",
        "Slash Tongue",
        "Silent Portal",
      ],
      one: ["a"],
      two: ["a"],
      three: ["a"],
      four: ["a"],
      five: ["a"],
      six: ["a"],
      seven: ["a"],
      eight: ["a"],
      nine: ["a"],
    },
    spellsPerDay: {
      zero: 8,
      one: 6,
      two: 6,
      three: 6,
      four: 6,
      five: 6,
      six: 6,
      seven: 6,
      eight: 6,
      nine: 6,
    },
  },
  items: [
    "Mesmerist's Gloves",
    "Nolzure's Orb",
    "Vanisher Cloak",
    "GateBreaker Ballista Bolt",
  ],
};
