const Arn: ICharacter = {
  id: "1",
  name: "Arn Hachem",
  type: ["Human", "Sanctified", "Deathless", "Spellstitched", "Archlich"],
  hitPoints: {
    dieSize: 12,
    total: 321,
    damage: 0,
    temporary: 0,
  },
  initiative: { misc: 0 },
  armorClass: {
    armor: 5,
    shield: 4,
    dexterity: 12,
    size: 0,
    naturalArmor: 5,
    deflection: 4,
    misc: 0,
  },
  damageReduction: {
    amount: 15,
    weakness: "bludgeoning, chaotic",
  },
  spellResistance: 27,
  energyResistance: {
    acid: 0,
    cold: null,
    electricity: null,
    fire: 0,
    sonic: 0,
  },
  saves: {
    fortitude: {
      base: 16,
      magic: 0,
      misc: 6,
      ability: "charisma",
    },
    reflex: {
      base: 10,
      magic: 0,
      misc: 6,
      ability: "dexterity",
    },
    will: {
      base: 18,
      magic: 7,
      misc: 6,
      ability: "wisdom",
    },
  },
  size: "Medium",
  alignment: "Lawful-Good",
  abilities: {
    score: {
      strength: 18,
      dexterity: 24,
      constitution: null,
      intelligence: 22,
      wisdom: 17,
      charisma: 35,
    },
    primary: "charisma" as
      | "strength"
      | "dexterity"
      | "constitution"
      | "intelligence"
      | "wisdom"
      | "charisma",
  },
  speed: { land: 40, fly: 0, swim: 0, burrow: 0 },
  classes: [
    {
      name: "Sorcerer",
      level: 1,
      magic: {
        spellcastingAbility: "charisma",
        casterLevel: 26,
        spellRefs: [
          { id: "1", level: 0, spontaneous: true },
          { id: "1", level: 0, spontaneous: false, prepped: 0, numUsed: 0 },
          { id: "2", level: 0, spontaneous: true },
          { id: "2", level: 0, spontaneous: false, prepped: 0, numUsed: 0 },
          { id: "3", level: 0, spontaneous: true },
          { id: "4", level: 0, spontaneous: true },
          { id: "5", level: 0, spontaneous: true },
          { id: "5", level: 0, spontaneous: false, prepped: 0, numUsed: 0 },
          { id: "6", level: 0, spontaneous: true },
          { id: "6", level: 0, spontaneous: false, prepped: 0, numUsed: 0 },
          { id: "7", level: 0, spontaneous: true },
          { id: "8", level: 0, spontaneous: true },
          { id: "9", level: 0, spontaneous: true },
          { id: "10", level: 0, spontaneous: true },
          { id: "11", level: 0, spontaneous: true },
          { id: "12", level: 0, spontaneous: true },
          { id: "12", level: 0, spontaneous: false, prepped: 0, numUsed: 0 },
          { id: "13", level: 0, spontaneous: true },
          { id: "13", level: 0, spontaneous: false, prepped: 0, numUsed: 0 },
        ],
        slotsPerDay: [8, 6, 6, 6, 6, 6, 6, 6, 6, 6],
        slotsUsed: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
    },
    { name: "Mindtender", level: 2 },
    { name: "Fleshwarper", level: 2 },
    { name: "Malconvoker", level: 8 },
    { name: "Binder", level: 1 },
    {
      name: "Bard",
      level: 1,
      magic: {
        spellcastingAbility: "charisma",
        casterLevel: 1,
        spellRefs: [
          { id: "10", level: 0, spontaneous: true },
          { id: "145", level: 0, spontaneous: true },
          { id: "146", level: 0, spontaneous: true },
        ],
        slotsPerDay: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        slotsUsed: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
    },
    { name: "Master Of Masks", level: 5 },
    { name: "Voidcaller", level: 1 },
  ],
  skillRefs: [
    {
      id: "0",
      ranks: 0,
      miscModifier: 4,
      classSkill: true,
    },
    {
      id: "1",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },
    {
      id: "2",
      ranks: 24,
      miscModifier: 13,
      classSkill: true,
    },
    {
      id: "3",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },
    {
      id: "4",
      ranks: 15,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "43",
      ranks: 17,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "5",
      ranks: 13,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "6",
      ranks: 10,
      miscModifier: 12,
      classSkill: true,
    },
    {
      id: "7",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },
    {
      id: "8",
      ranks: 24,
      miscModifier: 9,
      classSkill: true,
    },
    {
      id: "9",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "10",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "11",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "12",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },

    {
      id: "13",
      ranks: 20,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "14",
      ranks: 0,
      miscModifier: 13,
      classSkill: false,
    },
    {
      id: "15",
      ranks: 1,
      miscModifier: 12,
      classSkill: true,
    },
    {
      id: "16",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "31",
      ranks: 20,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "33",
      ranks: 8,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "44",
      ranks: 10,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "39",
      ranks: 23,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "35",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "17",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },
    {
      id: "18",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },
    {
      id: "19",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "45",
      ranks: 9,
      miscModifier: 16,
      classSkill: true,
    },
    {
      id: "40",
      ranks: 20,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "41",
      ranks: 1,
      miscModifier: 0,
      classSkill: true,
    },
    {
      id: "20",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },
    {
      id: "21",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },
    {
      id: "22",
      ranks: 6,
      miscModifier: 18,
      classSkill: true,
    },
    {
      id: "23",
      ranks: 7,
      miscModifier: 2,
      classSkill: true,
    },
    {
      id: "24",
      ranks: 20,
      miscModifier: 2,
      classSkill: true,
    },
    {
      id: "25",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },
    {
      id: "42",
      ranks: 0,
      miscModifier: 23,
      classSkill: true,
    },
    {
      id: "26",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },
    {
      id: "27",
      ranks: 0,
      miscModifier: 8,
      classSkill: false,
    },
    {
      id: "28",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },
    {
      id: "29",
      ranks: 0,
      miscModifier: 2,
      classSkill: true,
    },
    {
      id: "30",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
    },
  ],
  skillSynergyRefs: [
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
  ],
  characterAbilities: {
    active: [
      { name: "Light Ray", type: "supernatural" },
      { name: "Paralyzing Touch", type: "supernatural" },
      { name: "Positive Energy Touch", type: "supernatural" },
      { name: "Turn Undead", type: "supernatural" },
    ],
    passive: [{ name: "Aura Of Menace", type: "supernatural" }],
  },
  slaRefs: [
    { id: "14", level: 1, uses: 4, frequency: "day", numUsed: 0 },
    { id: "15", level: 2, uses: 4, frequency: "day", numUsed: 0 },
  ],
  itemRefs: [{ id: "1" }],
};

export default Arn;
