const Ig = {
  id: "2",
  name: "Ig Nallah",
  type: ["Sanctified", "Aboleth", "Demigod"],
  hitPoints: {
    dieSize: 12,
    total: 399,
  },
  armorClass: {
    armor: 4,
    shield: 4,
    dexterity: 0,
    size: 0,
    naturalArmor: 36,
    deflection: 7,
    misc: 10,
  },
  defense: {
    damageReduction: {
      amount: 10,
      weakness: "evil",
    },
    spellResistance: 32,
    energyResistance: {
      acid: 0,
      cold: 20,
      electricity: 20,
      fire: null,
      sonic: 0,
    },
    saves: {
      fortitude: {
        base: 19,
        magic: 0,
        misc: 2,
      },
      reflex: {
        base: 12,
        magic: 0,
        misc: 19,
      },
      will: {
        base: 26,
        magic: 0,
        misc: 20,
      },
    },
  },
  size: "Huge",
  alignment: "Lawful-Good",
  abilities: {
    score: {
      strength: 40,
      dexterity: 10,
      constitution: 24,
      intelligence: 47,
      wisdom: 54,
      charisma: 24,
    },
    primary: "wisdom" as
      | "strength"
      | "dexterity"
      | "constitution"
      | "intelligence"
      | "wisdom"
      | "charisma",
  },
  speed: 100,
  class: [
    { name: "Archivist", level: 1 },
    { name: "Contemplative", level: 1 },
    { name: "Aboleth Savant", level: 4 },
    { name: "Dungeon Lord", level: 5 },
    { name: "Runecaster", level: 9 },
    { name: "Herald of the Outer Spheres", level: 1 },
  ],
  skills: [
    {
      name: "Appraise",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 1,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Balance",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Bluff",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Climb",
      ability: "strength",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: true,
      display: true,
    },
    {
      name: "Concentration",
      ability: "charisma",
      ranks: 14,
      miscModifier: 7,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Stone Carving",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 7,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Runestone",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Decipher Script",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Diplomacy",
      ability: "charisma",
      ranks: 0,
      miscModifier: 4,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Disable Device",
      ability: "intelligence",
      ranks: 1,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Diguise",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Escape Artist",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Forgery",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 1,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Gather Information",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Handle Animal",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Heal",
      ability: "wisdom",
      ranks: 10,
      miscModifier: 3,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Hide",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: true,
      display: false,
    },
    {
      name: "Intimidate",
      ability: "charisma",
      ranks: 0,
      miscModifier: 4,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Jump",
      ability: "strength",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: true,
      display: true,
    },
    {
      name: "Knowledge Arcana",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Knowledge Architecure and Engineering",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Knowledge Religion",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Knowledge Planes",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Knowledge Nature",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Listen",
      ability: "wisdom",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Move Silently",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: false,
    },
    {
      name: "Open Lock",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: true,
      display: false,
    },
    {
      name: "Perception",
      ability: "wisdom",
      ranks: 25,
      miscModifier: 5,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Ride",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Search",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Sense Motive",
      ability: "wisdom",
      ranks: 25,
      miscModifier: 3,
      classSkill: true,
      armorCheck: false,
      display: true,
    },

    {
      name: "Sleight of Hand",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: false,
    },

    {
      name: "Spellcraft",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Spot",
      ability: "wisdom",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Stealth",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 23,
      classSkill: true,
      armorCheck: true,
      display: true,
    },
    {
      name: "Survival",
      ability: "wisdom",
      ranks: 0,
      miscModifier: 11,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Swim",
      ability: "strength",
      ranks: 0,
      miscModifier: 8,
      classSkill: true,
      armorCheck: true,
      display: true,
    },
    {
      name: "Use Magic Device",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Use Rope",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
  ],
  characterAbilities: {
    active: [
      { name: "Light Ray", type: "supernatural" },
      { name: "Break Enchantment", type: "supernatural" },
      { name: "Bite of the King", type: "supernatural" },
    ],
    passive: [
      { name: "Aura Of Menace", type: "supernatural" },
      { name: "Automatic Action", type: "divine" },
    ],
  },
  spellcaster: true,
  magic: {
    type: {
      arcane: false,
      divine: true,
    },
    slaRefs: [{ id: "srd33", level: 8, uses: 3, frequency: "day" }],
    slas: {
      zero: "",
      one: [],
      two: [],
      three: [],
      four: [
        { name: "Hallucinatory Terrain", uses: 3, frequency: "day" },
        { name: "Invisibility, Greater", uses: 3, frequency: "day" },
      ],
      five: [
        { name: "Passwall", uses: 3, frequency: "day" },
        { name: "Scrying", uses: 3, frequency: "day" },
      ],
      six: [
        { name: "Forbiddance", uses: 3, frequency: "day" },
        { name: "Guards and Wards", uses: 3, frequency: "day" },
        { name: "Scry Location", uses: 3, frequency: "day" },
      ],
      seven: [{ name: "Righteous Smite", uses: 3, frequency: "day" }],
      eight: [{ name: "Flash Flood", uses: 3, frequency: "day" }],
      nine: [{ name: "Hold Monster, Mass", uses: 3, frequency: "day" }],
    },
    spellRefs: [
      { id: "srd11", level: 0, innate: false },
      { id: "srd93", level: 1, innate: false },
      { id: "srd118", level: 3, innate: false },
      { id: "srd43", level: 5, innate: false },
      { id: "srd88", level: 5, innate: false },
    ],
    spells: {
      zero: ["Know Direction"],
      one: ["Goodberry"],
      two: ["Mark of the Outcast", "Enthrall"],
      three: ["Tongues"],
      four: ["Vampiric Touch", "Sending"],
      five: ["Baleful Polymorph"],
      six: ["Heroes Feast", "Dream"],
      seven: ["Stone to Flesh", "Aspect of the Deity"],
      eight: ["Swallow", "Crown of Glory"],
      nine: ["Trap the Soul", "Aspect of the Deity, Greater"],
    },
    spellbook: {
      zero: [
        "Create Water",
        "Cure Minor Wounds",
        "Detect Magic",
        "Detect Poison",
        "Guidance",
        "Inflict Minor Wounds",
        "Light",
        "Mending",
        "Purify Food and Drink",
        "Read Magic",
        "Resistance",
        "Virtue",
        "Amenuensis",
        "No Light",
        "Preserve Organ",
        "Slash Tongue",
      ],
      one: [
        "Cure Light Wounds",
        "Hide from Undead",
        "Purify Water",
        "Divine Favor",
        "Obscuring Mist",
        "Wings of the Sea",
        "Stupor",
        "Shield of Faith",
        "Conviction",
        "Detect Evil",
        "Omen of Peril",
        "Resurgence",
        "Ray of Hope",
        "Sign",
        "Vision of Heaven",
        "Resist Planar Alignment",
        "Sanctuary",
        "Guiding Light",
        "Healthful Rest",
        "Ebon Eyes",
      ],
      two: [
        "Cure Moderate Wounds",
        "Consecrate",
        "Darkness",
        "Silence",
        "Inflict Moderate Wounds",
      ],
      three: [
        "Dispel Magic",
        "Helping Hand",
        "Meld Into Stone",
        "Stone Shape",
        "Air Breathing",
      ],
      four: [
        "Divine Power",
        "Dismissal",
        "Dimensional Anchor",
        "Cure Critical Wounds",
        "Shape Metal",
      ],
      five: ["Symbol of Pain", "Symbol of Sleep", "Hallow", "Wall of Stone"],
      six: [
        "Banishment",
        "Blade Barrier",
        "Dispel Magic, Greater",
        "Heal",
        "Harm",
      ],
      seven: [
        "Control Weather",
        "Dictum",
        "Refuge",
        "Symbol of Stunning",
        "Tomb of Light",
        "Brilliant Blade",
        "Restoration, Mass",
      ],
      eight: [
        "Holy Aura",
        "Symbol of Insanity",
        "Visions of the Future",
        "Spell Immunity, Greater",
        "Cure Critical Wounds, Mass",
      ],
      nine: ["Soul Bind", "Energy Drain", "True Resurrection"],
    },
    spellsPerDay: {
      zero: 4,
      one: 5,
      two: 5,
      three: 5,
      four: 5,
      five: 5,
      six: 5,
      seven: 5,
      eight: 4,
      nine: 4,
    },
  },
  itemRefs: [],
};

export default Ig;
