const Ig: ICharacter = {
  id: "2",
  name: "Ig Nallah",
  type: ["Sanctified", "Aboleth", "Demigod"],
  hitPoints: {
    dieSize: 12,
    total: 399,
    damage: 0,
    temporary: 0,
  },
  armorClass: {
    armor: 4,
    shield: 4,
    dexterity: 0,
    size: 0,
    naturalArmor: 36,
    deflection: 7,
    misc: 10,
  },
  damageReduction: {
    amount: 10,
    weakness: "evil",
  },
  spellResistance: 32,
  energyResistance: {
    acid: 0,
    cold: 20,
    electricity: 20,
    fire: null,
    sonic: 0,
  },
  saves: {
    fortitude: {
      base: 19,
      magic: 0,
      misc: 2,
      ability: "constitution",
    },
    reflex: {
      base: 12,
      magic: 0,
      misc: 19,
      ability: "intelligence",
    },
    will: {
      base: 26,
      magic: 0,
      misc: 20,
      ability: "wisdom",
    },
  },
  size: "Huge",
  alignment: "Lawful-Good",
  abilities: {
    score: {
      strength: 40,
      dexterity: 10,
      constitution: 24,
      intelligence: 47,
      wisdom: 54,
      charisma: 24,
    },
    primary: "wisdom" as
      | "strength"
      | "dexterity"
      | "constitution"
      | "intelligence"
      | "wisdom"
      | "charisma",
  },
  speed: 100,
  class: [
    { name: "Archivist", level: 1 },
    { name: "Contemplative", level: 1 },
    { name: "Aboleth Savant", level: 4 },
    { name: "Dungeon Lord", level: 5 },
    { name: "Runecaster", level: 9 },
    { name: "Herald of the Outer Spheres", level: 1 },
  ],
  skills: [
    {
      name: "Appraise",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 1,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Balance",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Bluff",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Climb",
      ability: "strength",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: true,
      display: true,
    },
    {
      name: "Concentration",
      ability: "charisma",
      ranks: 14,
      miscModifier: 7,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Stone Carving",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 7,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Runestone",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Decipher Script",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Diplomacy",
      ability: "charisma",
      ranks: 0,
      miscModifier: 4,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Disable Device",
      ability: "intelligence",
      ranks: 1,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Diguise",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Escape Artist",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Forgery",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 1,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Gather Information",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Handle Animal",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Heal",
      ability: "wisdom",
      ranks: 10,
      miscModifier: 3,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Hide",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: true,
      display: false,
    },
    {
      name: "Intimidate",
      ability: "charisma",
      ranks: 0,
      miscModifier: 4,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Jump",
      ability: "strength",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: true,
      display: true,
    },
    {
      name: "Knowledge Arcana",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Knowledge Architecure and Engineering",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Knowledge Religion",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Knowledge Planes",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Knowledge Nature",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Listen",
      ability: "wisdom",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Move Silently",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: false,
    },
    {
      name: "Open Lock",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: true,
      display: false,
    },
    {
      name: "Perception",
      ability: "wisdom",
      ranks: 25,
      miscModifier: 5,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Ride",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Search",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Sense Motive",
      ability: "wisdom",
      ranks: 25,
      miscModifier: 3,
      classSkill: true,
      armorCheck: false,
      display: true,
    },

    {
      name: "Sleight of Hand",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: false,
    },

    {
      name: "Spellcraft",
      ability: "intelligence",
      ranks: 24,
      miscModifier: 1,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Spot",
      ability: "wisdom",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Stealth",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 23,
      classSkill: true,
      armorCheck: true,
      display: true,
    },
    {
      name: "Survival",
      ability: "wisdom",
      ranks: 0,
      miscModifier: 11,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Swim",
      ability: "strength",
      ranks: 0,
      miscModifier: 8,
      classSkill: true,
      armorCheck: true,
      display: true,
    },
    {
      name: "Use Magic Device",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Use Rope",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
  ],
  characterAbilities: {
    active: [
      { name: "Light Ray", type: "supernatural" },
      { name: "Break Enchantment", type: "supernatural" },
      { name: "Bite of the King", type: "supernatural" },
    ],
    passive: [
      { name: "Aura Of Menace", type: "supernatural" },
      { name: "Automatic Action", type: "divine" },
    ],
  },
  magic: {
    casterLevel: 22,
    type: {
      arcane: false,
      divine: true,
    },
    slaRefs: [{ id: "33", level: 8, uses: 3, frequency: "day" }],
    spellRefs: [
      { id: "11", level: 0, innate: false },
      { id: "93", level: 1, innate: false },
      { id: "118", level: 3, innate: false },
      { id: "43", level: 5, innate: false },
      { id: "88", level: 5, innate: false },
    ],
    spellsPerDay: [4, 5, 5, 5, 5, 5, 5, 4, 4],
  },
  itemRefs: [],
};

export default Ig;
