const Zachariah = {
  id: "3",
  name: "Zachariah Asalam",
  type: ["Silverbrow Human"],
  hitPoints: {
    dieSize: 4,
    total: 5,
  },
  armorClass: {
    armor: 0,
    shield: 0,
    dexterity: 4,
    size: 0,
    naturalArmor: 0,
    deflection: 0,
    misc: 0,
  },
  defense: {
    damageReduction: {
      amount: 0,
      weakness: "",
    },
    spellResistance: 0,
    energyResistance: {
      acid: 0,
      cold: 0,
      electricity: 0,
      fire: 0,
      sonic: 0,
    },
    saves: {
      fortitude: {
        base: 0,
        magic: 0,
        misc: 2,
      },
      reflex: {
        base: 0,
        magic: 0,
        misc: 0,
      },
      will: {
        base: 2,
        magic: 0,
        misc: 0,
      },
    },
  },
  size: "Medium",
  alignment: "Chaotic-Good",
  abilities: {
    score: {
      strength: 10,
      dexterity: 18,
      constitution: 14,
      intelligence: 19,
      wisdom: 12,
      charisma: 10,
    },
    primary: "intelligence" as
      | "strength"
      | "dexterity"
      | "constitution"
      | "intelligence"
      | "wisdom"
      | "charisma",
  },
  speed: 30,
  class: [{ name: "Wizard", level: 1 }],
  skills: [
    {
      name: "Appraise",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Balance",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Bluff",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Climb",
      ability: "strength",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Concentration",
      ability: "constitution",
      ranks: 4,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Decipher Script",
      ability: "intelligence",
      ranks: 4,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Diplomacy",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Disable Device",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Diguise",
      ability: "charisma",
      ranks: 0,
      miscModifier: 2,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Escape Artist",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Forgery",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Gather Information",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Handle Animal",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },

    {
      name: "Heal",
      ability: "wisdom",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Hide",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: false,
    },
    {
      name: "Intimidate",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Jump",
      ability: "strength",
      ranks: 0,
      miscModifier: 10,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Knowledge Arcana",
      ability: "intelligence",
      ranks: 4,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Knowledge Local(Halruaa)",
      ability: "intelligence",
      ranks: 4,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Knowledge Nature",
      ability: "intelligence",
      ranks: 4,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Listen",
      ability: "wisdom",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: false,
    },
    {
      name: "Move Silently",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: false,
    },
    {
      name: "Open Lock",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Perception",
      ability: "wisdom",
      ranks: 4,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Ride",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Search",
      ability: "intelligence",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: false,
    },
    {
      name: "Sense Motive",
      ability: "wisdom",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Sleight of Hand",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Spellcraft",
      ability: "intelligence",
      ranks: 4,
      miscModifier: 0,
      classSkill: true,
      armorCheck: false,
      display: true,
    },
    {
      name: "Spot",
      ability: "wisdom",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: false,
    },
    {
      name: "Stealth",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Survival",
      ability: "wisdom",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Swim",
      ability: "strength",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: true,
      display: true,
    },
    {
      name: "Use Magic Device",
      ability: "charisma",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
    {
      name: "Use Rope",
      ability: "dexterity",
      ranks: 0,
      miscModifier: 0,
      classSkill: false,
      armorCheck: false,
      display: true,
    },
  ],
  characterAbilities: {
    active: [],
    passive: ["Spontaneous Dispelling"],
  },
  spellcaster: true,
  magic: {
    casterLevel: 1,
    type: {
      arcane: true,
      divine: false,
    },
    slaRefs: [],
    spellRefs: [
      { id: "9", level: 0, innate: false },
      { id: "129", level: 0, innate: false },
      { id: "2", level: 0, innate: false },
      { id: "130", level: 0, innate: false },
      { id: "124", level: 0, innate: false },
      { id: "131", level: 0, innate: false },
      { id: "118", level: 0, innate: false },
      { id: "4", level: 0, innate: false },
      { id: "123", level: 0, innate: false },
      { id: "134", level: 0, innate: false },
      { id: "125", level: 0, innate: false },
      { id: "135", level: 0, innate: false },
      { id: "136", level: 0, innate: false },
      { id: "145", level: 0, innate: false },
      { id: "7", level: 0, innate: false },
      { id: "5", level: 0, innate: false },
      { id: "1", level: 0, innate: false },
      { id: "6", level: 0, innate: false },
      { id: "146", level: 0, innate: false },
      { id: "12", level: 0, innate: false },
      { id: "13", level: 0, innate: false },
      { id: "142", level: 0, innate: false },
      { id: "143", level: 0, innate: false },
      { id: "126", level: 0, innate: false },
      { id: "8", level: 0, innate: false },
      { id: "139", level: 0, innate: false },
      { id: "122", level: 0, innate: false },
      { id: "19", level: 1, innate: false },
      { id: "147", level: 1, innate: false },
      { id: "148", level: 1, innate: false },
      { id: "149", level: 1, innate: false },
      { id: "150", level: 1, innate: false },
      { id: "151", level: 1, innate: false },
      { id: "152", level: 1, innate: false },
    ],
    spellsPerDay: {
      zero: 3,
      one: 1,
      two: 0,
      three: 0,
      four: 0,
      five: 0,
      six: 0,
      seven: 0,
      eight: 0,
      nine: 0,
    },
  },
  itemRefs: [],
};

export default Zachariah;
