import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import { Navigate, RouterProvider, createBrowserRouter } from "react-router";
import { RecoilRoot } from "recoil";
import { SWRConfig } from "swr";

import ActiveAndPassiveAbilities from "./components/ActiveAndPassiveAbilities/ActiveAndPassiveAbilities";
import { Items } from "./components/Items";
import { Main } from "./components/Main";
import { NotFound } from "./components/NotFound";
import { Skills } from "./components/Skills/Skills";
import { Spells } from "./components/Spells";
import LoadApp from "./components/App";

import "./index.css";
// Register the PWA service worker generated by vite-plugin-pwa
import { registerSW } from 'virtual:pwa-register';


const router = createBrowserRouter([
  {
    path: "/",
    element: <LoadApp />,
    children: [
      { index: true, element: <Navigate to="/main" replace /> },
      { path: "main", element: <Main /> },
      { path: "skills", element: <Skills /> },
      { path: "items", element: <Items /> },
      { path: "spells", element: <Spells /> },
      { path: "abilities", element: <ActiveAndPassiveAbilities /> },
      { path: "*", element: <NotFound /> },
    ],
  },
]);

const container = document.getElementById("root");
const root = createRoot(container!);

root.render(
  <StrictMode>
    <RecoilRoot>
      <SWRConfig
        value={{
          fetcher: (...args: Parameters<typeof fetch>) =>
            fetch(...args).then((res) => res.json()),
        }}
      >
        <RouterProvider router={router} />
      </SWRConfig>
    </RecoilRoot>
  </StrictMode>,
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
// Register the service worker in production so the app can work offline and be a PWA.
// Uses the Vite built base URL via import.meta.env.BASE_URL inside serviceWorker module.
// register the PWA service worker with immediate update strategy
const updateSW = registerSW({ immediate: true });
